### ISSUE TITLE
Feature: slider instead of checkbox for falling

### ISSUE THREAD

**Issue by STyx2909** [Spartan190/Adv_Wound_Reaction#1]
Instead of a checkbox for player falling on ground, while injured/in pain, have a treshold slider to fine tunes when this happen.

**Comment by Spartan190** [comment]
Currently this is coupled with the state of the legs or body. If the units body or legs are in critical state (above the pain/damage threshold) then the unit can no longer stand. The check box is to determine if the unit will actually fall (physics) or just forced to trigger the lay down animation.

If you mean the general setting if the unit should be forced to be down that's also tied with these states.

**Comment by STyx2909** [comment]
Re-opening this.
Checked parameters.

In my opinion, a Pain Treshold for each body location (head, torso, arms and legs) could be an interesting feature to add, as it would allow a variety of fine tuning for players in regard to the pain level in such areas.

The general pain treshold is... well... too generic. ;-P

**Comment by Spartan190** [comment]
Well sadly there is currently no way to add a pain level threshold per bodypart. ACE only has a global perceived pain level for the unit but not per body part.
Only the damage is recorded per body part that's why there is sliders for the damage per body part but not for the pain level.

**Comment by STyx2909** [comment]
Got it.
